### ISSUE TITLE
Output Panel does not show first character

### ISSUE THREAD

**Issue by MMore** [tarzan/sublime-text-elixir-tests#4]
Hey,
I started using your plugin and I noticed that the first char in the output of the panel is not shown (see screenshot). When I copy the text from the panel I can see that that all information is there, it's just not shown. Any idea what the reason could be? I tried already changing sizes, themes, color schemes etc.

![Screenshot 2020-06-07 at 11 14 18](https://user-images.githubusercontent.com/172760/83964937-6165e680-a8b0-11ea-97a8-1b707f802767.png)

PS: I am using `Version 3.2.2, Build 3211` on MacOS `10.15.4` (non-retina).

**Comment by tarzan** [comment]
Thanks for reporting this. I haven't seen the problem you're describing and I'm running the same version of Sublime on MacOS. 
I'm not really proficient in Python, hence the shameless rip-off from ruby-tests, so I'm unsure of how to try and debug something like this. Maybe, what you're seeing is interference with another SublimePlugin or Package? Could you try it with a clean install of Sublime?

**Comment by MMore** [comment]
Clean install works. But I am too lazy to figure out the exact problem... Thank you anyway!
